### PR TITLE
Updating swinject dependency to 2.0.0, also bumping version to 2.

### PR DESCRIPTION
**Pull request by gasthana0**

### CODE REVIEW

**Comment by gasthana0** [comment]
Hi Yoichi,

Could you please take a look at this.

Gaurav

**Comment by yoichitgy** [comment]
Hi @gasthana0, thank you for making a pull request, and i'm sorry for missing the pull request. (I was notified your pull request by email, and was looking for it in the repo in Swinject organization.) Please feel free to make pull request to the repos under Swinject organization too.

I'll check and merge your pull request soon.

**Comment by gasthana0** [comment]
thanks Yoichi.

**Comment by yoichitgy** [comment]
Thanks @gasthana0 for your pull request😃👍👍 I thought I should update SwinjectPropertyLoader to use Swinject v2, but I couldn't. Your pull request was very helpful!!!

**Pull request merged**
